---
#title: "Macroenometrics (44343)"
output:
  html_document:
    theme: united
    highlight: monochrome 
    number_sections: no
    toc: true
    toc_float: true
    #code_folding: show
    #self_contained: TRUE
---

  <br>

## Logistics
  
This

## "The plan"

The truth is that I would have preferred to delay the classes but finally we are going **to start the classes** as planned the **16th of April** at 9:00 (spanish time, UTC + 2 hours), but on-line.

I do not know if in your confinement site you have everything you need to follow the classes, if not, please tell me. Also, I have no experience teaching online, then **I will need your help to make the course work**.

My topic (VAR models) was planned to be delibered in 5 classes: 16th, 20th, 23th, 27th and 30th of April, from 8:30 to 10:30. I think it is better to keep the official schedule. Please see the [Schedulle](Schedulle) section of the web.

My plan/intention is to meet you 5 times, but instead to deliver a traditional class where the teacher talks about a subject, I think it would be better if you read the materials firts and we dedicate the session to solve doubts and provide feedback. In fact my classes, even when I teach face to face, have always an important component of making and solving questions. We will see how it works on-line and in English.


## Logistics

During the mini-course we are going to use:


- [Aula Virtual site for Macroeconometrics](https://aulavirtual.uv.es/course/view.php?id=9759). From here we will use Black Board Collaborate to make online meetings

- [Et]

Dear students,

What a situation we are living!! The truth is that I would have preferred to delay the classes but finally we are going to start the classes as planned the 16th of April, but on-line. I do not know if in your confinement site you have everything you need to follow the classes, if not, please tell me. Also, I have no experience teaching online, then I will need your help to make the course work.

My topic (VAR models) was planned to be delibered in 5 classes: 16th, 20th, 23th, 27th and 30th of April, from 8:30 to 10:30. I think it is better to keep the official schedule, then we will have our **first online meeting** (using BlackBorad Collaborate) the **Thursday 16th of April at 9:00** (time of Spain, UTC+2 hours).

My plan/intention is to meet you 5 times, but instead of deliver a traditional class where the teacher talks about a subject, I think it would be better if you read first the materials and dedicate the session to solve doubts. In fact my classes, even when I teach face to face, have always an important component of making and solving questions. We will see how it works on-line and in English.

Of course you are interested in the marks. My mini-course contributes 1 ECTS out of 5, then the VAR topic represents the 20% of your Macroeconometrics mark. My intention ins not to make an exam, Mariam does already one, then my 20% will come from an assignment. Obviously the assignmente will consist on estimating, validating and using a VAR model. 

The first class should be devoted to explain:

- how to deliver the VAR assignment

- a litle bite of R & Rmarkdown (because you will have to deliver your assignment using Rmarkdown)

- what is a VAR?

- When the VARs were started to de used in Macroeconomics?

- How we can estimate 

The second class ... we will see how classes works!!

