---
#title: "Macroenometrics (44343)"
output:
  html_document:
    theme: united
    highlight: monochrome 
    number_sections: no
    toc: true
    toc_float: true
    #code_folding: show
    #self_contained: TRUE
---

<br>


During the mini-course we are going to use, aside from this website, the following:

### Resources:

- [**`Aula Virtual site for Macroeconometrics`**](https://aulavirtual.uv.es/course/view.php?id=9759): from here we will use Black Board Collaborate to make on-line meetings

- [**`Etherpad`**](https://etherpad.wikimedia.org/p/var_18): during the course we are going to make some work with R, we will use an etherpad to collaborate with the code.

<br>

------------------

### Materials:

- [**`Slides`**](https://perezp44.github.io/VAR-models-web/03-Slides.html): the slides that I used last year to teach the course. Last, and previous, years the teaching was not on-line.

- [**`Lab`**](https://perezp44.github.io/VAR-models-web/04-Lab-Gali.html). A document that replicates the [Gali(1999) paper](http://www.crei.cat/wp-content/uploads/users/pages/jgaer99.pdf), providing an example of use structural VAR methodology using R and the [vars package](http://cran.r-project.org/web/packages/vars/vars.pdf).

<br>

------------------------------

### More resources:

The assignment of the course should be delivered as an `Rproject` and written in `Rmarkdown`, then you should know what they are. Don't worry I will explain this the first day. It's funny and really useful. You could read this tutorials. Sorry there comes from another course I have, then there are in Spanish. Sorry I have no time to translate but internet is plenty of resources in English.

- [**`Tutorial about Rprojects`**](https://perezp44.github.io/VAR-models-web/tt_01_primeros_pasos-con-R.html): section 3 of this tutorial explain how to make an Rprojects and why it is useful They have also references in English



- [**`Rmarkdown Tutorial`**](https://perezp44.github.io/VAR-models-web/tt_02_Rmarkdown.html): an introduction to Rmarkdown. Also plenty of references in English

---------------------------------



<br><br>

---------------------------------
    
### Bibliography

**The slides and the course are based on the following documents:**  
(and probably some others that I have not remembered at the time of the final making. Thanks to all of them)


- Amisano, G., and Giannini, C. (1997). [Topics in Structural VAR Econometrics](http://www.springer.com/gp/book/9783662027578). Springer. 
- Bjørnland, H. C., and Thorsrud, L. (2015). [Applied Time Series for Macroeconomics](http://www.gyldendal.no/Faglitteratur/OEkonomi-og-administrasjon/Samfunnsoekonomi/Applied-time-series-for-macroeconomics-2.-utg),  Gyldendal Akademisk. 
- Gali, J. (1999), [Technology, Employment, and the Business Cycle: Do Technology Shocks
Explain Aggregate Fluctuations?](http://crei.cat/people/gali/jgaer99.pdf), American Economic Review, 89, 249-271.
- Gottschalk, J. (2001), [An Introduction into the SVAR Methodology: Identification, Interpretation and Limitations of SVAR models](https://www.ifw-members.ifw-kiel.de/publications/an-introduction-into-the-svar-methodology-identification-interpretation-and-limitations-of-svar-models/kap1072.pdf), Kiel Working Paper nº 1072
- Kilian, L. (2011),  [Structural Vector Autoregression](https://ideas.repec.org/p/cpr/ceprdp/8515.html), CEPR Discussion Paper Series n^o^ 8515.
- Sims, C.A. (1980), [Macroeconomics and Reality](https://ideas.repec.org/a/ecm/emetrp/v48y1980i1p1-48.html), Econometrica, 48, 1-48
- Lütkepohl, H. (2005), [New Introduction to Multiple Time Series Analysis](http://www.springer.com/gp/book/9783540401728). Springer: New York.
- Lütkepohl, H. (2011), [Vector Autoregressive Models](http://cadmus.eui.eu/bitstream/handle/1814/19354/ECO_2011_30.pdf), EUI Working Paper ECO2011/30
- Pfaff, B. (2008a), [VAR, SVAR and SVEC Models: Implementation Within R Package vars](http://www.jstatsoft.org/v27/i04/paper), Journal of Statistical Software, 27(4)
- Pfaff, B. (2008b), [Analysis of Integrated and Cointegrated Time Series with R](http://www.springer.com/gp/book/9780387759661), Springer
- Pfaff, B. (2014), [Package 'vars'](http://cran.r-project.org/web/packages/vars/vars.pdf), CRAN R package.
- Stock, J. H. (2008), [Recent Developments in Structural VAR Modelling](http://www.nber.org/WNE/slides7-14-08/Lecture7.pdf), NBER Summer Institute